24

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -30,23 +30,28 @@ jobs:
         id: check_tag_exists
         run: |
           TAG="release-${{ github.run_number }}-${{ github.sha }}"
-          git tag -l | grep -q "$TAG" && echo "tag_exists=true" >> $GITHUB_ENV || echo "tag_exists=false" >> $GITHUB_ENV
+          if git tag -l | grep -q "$TAG"; then
+            echo "Tag already exists. Skipping release creation."
+            echo "tag_exists=true" >> $GITHUB_ENV 
+          else 
+            echo "tag_exists=false" >> $GITHUB_ENV 
+          fi
 
-      - name: Create Release
-        id: create_release
-        if: env.tag_exists == 'false'
-        uses: actions/create-release@v1
+      - name: Create Release  
+        id: create_release  
+        if: env.tag_exists == 'false'  
+        uses: actions/create-release@v1  
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
         with:
-          tag_name: "release-${{ github.run_number }}-${{ github.sha }}"
-          release_name: Release ${{ github.run_number }}
-          draft: false
-          prerelease: false 
+          tag_name: "release-${{ github.run_number }}-${{ github.sha }}"  
+          release_name: Release ${{ github.run_number }}  
+          draft: false  
+          prerelease: false  
 
       - name: Upload Release Asset 
         id: upload-release-asset 
-        if: env.tag_exists == 'false'
+        if: env.tag_exists == 'false'  
         uses: actions/upload-release-asset@v1  
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
@@ -57,34 +62,34 @@ jobs:
           asset_content_type: application/vnd.debian.binary-package 
 
   build-macos:
-    runs-on: macos-latest
-    permissions: write-all
+    runs-on: macos-latest   
+    permissions: write-all   
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v3   
         with:
-          submodules: true
+          submodules: true   
+
+      - run: |   
+          brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }  
       
-      - run: |
-          brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }
+      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}   
       
-      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
-      
-      - run: cmake --build .
-      
-      - run: cmake --build . --target test
-      
-      - run: cmake --build . --target package
-      
-      - name: Check if tag exists for macOS 
-        id: check_tag_exists_macos 
-        run: |
-          TAG="release-${{ github.run_number }}-${{ github.sha }}"
-          if git tag -l | grep -q "$TAG"; then
+      - run: cmake --build .   
+
+      - run: cmake --build . --target test   
+
+      - run: cmake --build . --target package   
+
+      - name: Check if tag exists for macOS   
+        id: check_tag_exists_macos   
+        run: |  
+          TAG="release-${{ github.run_number }}-${{ github.sha }}"  
+          if git tag -l | grep -q "$TAG"; then 
             echo "tag_exists=true" >> $GITHUB_ENV;  
-          else
+          else 
             echo "tag_exists=false" >> $GITHUB_ENV;  
           fi  
-
+      
       - name: Create Release for macOS 
         id: create_release_macos 
         if: env.tag_exists == 'false'  
@@ -107,4 +112,4 @@ jobs:
           upload_url: ${{ steps.create_release_macos.outputs.upload_url }}  
           asset_path: ./helloworld-0.0.${{ github.run_number }}-macOS.pkg  
           asset_name: helloworld-0.0.${{ github.run_number }}-macOS.pkg  
-          asset_content_type: application/octet-stream  
+          asset_content_type: application/octet-stream 
